// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.Toolbox.Sas")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.Toolbox")>]
[<assembly: AssemblyDescriptionAttribute("F# Data-based library for various data access APIs.")>]
[<assembly: AssemblyVersionAttribute("0.19")>]
[<assembly: AssemblyFileVersionAttribute("0.19")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.Toolbox.Sas"
    let [<Literal>] AssemblyProduct = "FSharp.Data.Toolbox"
    let [<Literal>] AssemblyDescription = "F# Data-based library for various data access APIs."
    let [<Literal>] AssemblyVersion = "0.19"
    let [<Literal>] AssemblyFileVersion = "0.19"
